{{- $config := .Values.pvPvcMany }}
{{- range $i, $e := $config }}
{{- range $j, $namespace := $e.namespaces }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $e.pv.name }}-{{ $namespace }}
spec:
  capacity:
    storage: {{ default "8Gi" $e.pv.storage }}
  {{ toYaml $e.pv.spec | nindent 2 }}
  accessModes:
    - {{ default "ReadWriteMany" $e.pv.accessModes }} 
  volumeMode: {{ default "Filesystem" $e.pv.volumeMode }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $e.pvc.name }}
  namespace: {{ $namespace }}
spec:
  accessModes:
    - {{ default "ReadWriteMany" $e.pv.accessModes }} 
  resources:
    requests:
      storage: {{ default "8Gi" $e.pv.storage }}
  volumeName: {{ $e.pv.name }}-{{ $namespace }}
  volumeMode: {{ default "Filesystem" $e.pv.volumeMode }} 
{{- end}}
{{- end}}