{{- $config := .Values.pvcs }}
{{- range $i, $e := $config }}
{{- range $j, $namespace := $e.namespaces }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
  labels:
    configMap/name: {{ $e.name }}
    release/name: "{{ $.Release.Name }}"
    release/revision: "{{ $.Release.Revision }}"
spec:
  accessModes:
    - {{ default "ReadWriteMany" $e.accessModes }} 
  resources:
    requests:
    {{ if ((($e.resources).requests).storage) }}
      storage: {{ $e.resources.requests.storage }}
    {{ else }}
      storage: "8Gi"
    {{ end }}
  {{ if ($e.storageClassName) }}
  storageClassName: {{ $e.storageClassName }}
  {{ end }}
  {{ if ($e.volumeName) }}
  volumeName: {{ $e.volumeName }}
  {{ end }}
  volumeMode: {{ default "Filesystem" $e.volumeMode }} 
{{- end}}
{{- end}}