{{- $config := .Values.secret.basic }}
{{- range $i, $e := $config }}
{{- range $j, $f := $e.namespaces }}
{{- range $k, $g := $e.data.key }}
{{- range $l, $h := $e.data.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $f }}
{{- with $e.data }}
type: Opaque
data:
  {{ $g }}: {{ $h | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}