{{- $config := .Values.secret.basic }}
{{- range $i, $e := $config }}
{{- range $j, $f := $e.namespaces }}
{{- range $k, $g := $e.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $f }}
{{- with $e.data }}
type: Opaque
data:
  {{- toYaml .key | nindent 2 }}: {{- toYaml .value | b64enc }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}