{{- $config := .Values.secret.basic }}
{{- range $i, $e := $config }}
{{- range $namespace := $e.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
  labels:
    configMap/name: {{ $e.name }}
    chart/name: "{{ .Chart.Name }}"
    chart/version: "{{ .Chart.Version }}"
    release/name: "{{ .Release.Name }}"
    release/revision: "{{ .Release.Revision }}"
{{- with $e.data }}
type: Opaque
data:
  {{- range $key, $value := $e.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }} 
{{- end }}
{{- end }}
