{{- $config := .Values.secret.basic }}
{{- range $i, $e := $config }}
{{- range $namespace := $e.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
{{- with $e.data }}
type: Opaque
data:
  {{- range $key, $value := $e.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }} 
{{- end }}
{{- end }}
