{{- if .Values.secret }}
{{- $config := .Values.secret.dockerconfigjson }}
{{- range $i, $e := $config }}
{{- range $j, $f := $e.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $f }}
  labels:
    configMap/name: {{ $e.name }}
    chart/name: "{{ .Chart.Name }}"
    chart/version: "{{ .Chart.Version }}"
    release/name: "{{ .Release.Name }}"
    release/revision: "{{ .Release.Revision }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $e.dockerconfigjson }}
{{- end }}
{{- end }}
{{- end }}
