{{- $config := .Values.secret.basic }}
{{- range $i, $e := $config }}
{{- range $j, $f := $e.namespaces }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $f }}
{{- with $e.data }}
type: Opaque
data:
  {{- toYaml . | b64enc | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
