secrets:
  dockerconfigjson:
    regcred:
      namespaces:
        - namespaces1
        - namespaces2
      data:
        encode: eyJhdXRocyI6eyJiYW5hbmEuY29tIjp7ImF1dGgiOiAiWVdSdGFXNDZZV1J0YVc0PSJ9LCJjYWZlLm5ldC5iciI6eyJhdXRoIjogIllXUnRhVzQ2WVdSdGFXND0ifX19

