{{- if .Values.configMap }}
{{- $config := .Values.configMap.basic }}
{{- range $i, $e := $config }}
{{- range $j, $namespace := $e.namespaces }}
{{- if $e.data }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
  labels:
    configMap/name: {{ $e.name }}
    chart/name: "{{ .Chart.Name }}"
    chart/version: "{{ .Chart.Version }}"
    release/name: "{{ .Release.Name }}"
    release/revision: "{{ .Release.Revision }}"
data:
  {{- toYaml $e.data | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
