{{- if .Values.secret }}
{{- $config := .Values.secret.dockerconfigjson }}
{{- range $i, $e := $config }}
{{- range $j, $namespace := $e.namespaces }}
{{- if $e.dockerconfigjson }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
  labels:
    release/name: "{{ $.Release.Name }}"
    release/revision: "{{ $.Release.Revision }}"
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ $e.dockerconfigjson }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
