{{- if .Values.secret }}
{{- if .Values.secret.basic }}
{{- if .Values.secret.basic.opaque }}
{{- $config := .Values.secret.basic.opaque }}
{{- range $i, $e := $config }}
{{- range $j, $namespace := $e.namespaces }}
{{- if $e.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $e.name }}
  namespace: {{ $namespace }}
  labels:
    configMap/name: {{ $e.name }}
    release/name: "{{ $.Release.Name }}"
    release/revision: "{{ $.Release.Revision }}"
type: Opaque
data:
  {{- range $key, $value := $e.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }} 
{{- end }}
