{{- $config := .Values.opentelemetry.instrumentation }}
{{- range $i, $namespace := $config.namespaces }}
---
apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: otel-instrumentation
  namespace: {{ $namespace }}
spec:
  exporter:
    endpoint: http://{{ $config.defaultEndpoint }}:4317
    retrySettings:
      maxAttempts: {{ $config.retry.maxAttempts }}
      initialInterval: {{ $config.retry.initialInterval }}
      maxInterval: {{ $config.retry.maxInterval }}
      timeout: {{ $config.retry.timeout }}
  propagators:
    - tracecontext
    - baggage
    - b3
    - jaeger
  sampler:
    type: parentbased_traceidratio
    argument: "{{ default 0.25 $config.traceidratio }}"
  python:
    env:
      # Required if endpoint is set to 4317.
      # Python autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://{{ $config.defaultEndpoint }}:4318
  dotnet:
    env:
      # Required if endpoint is set to 4317.
      # Dotnet autoinstrumentation uses http/proto by default
      # See https://github.com/open-telemetry/opentelemetry-dotnet-instrumentation/blob/888e2cd216c77d12e56b54ee91dafbc4e7452a52/docs/config.md#otlp
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://{{ $config.defaultEndpoint }}:4318
  go:
    env:
      # Required if endpoint is set to 4317.
      # Go autoinstrumentation uses http/proto by default
      # so data must be sent to 4318 instead of 4317.
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://{{ $config.defaultEndpoint }}:4318
{{- end}}