{{- $policies := .Values.networkPolicy.policies }}
{{- range $name, $config := $policies }}
  {{- range $namespace := $config.namespaces }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
spec:
  podSelector: {{- toYaml (default dict $config.podSelector) | nindent 4 }}
  policyTypes:
    - {{ $config.policyType }}
  {{- if and (eq $config.policyType "Ingress") (or $config.namespaceSelectorLabel $config.internalNamespace) }}
  ingress:
    - from:
  {{- if $config.namespaceSelectorLabel }}
        - namespaceSelector:
            matchLabels:
{{ toYaml $config.namespaceSelectorLabel | indent 12 }}
  {{- end }}
  {{- if $config.internalNamespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
  {{- end }}
  {{- end }}
  {{- if and (eq $config.policyType "Egress") (or $config.namespaceSelectorLabel $config.internalNamespace) }}
  egress:
    - to:
  {{- if $config.namespaceSelectorLabel }}
        - namespaceSelector:
            matchLabels:
{{ toYaml $config.namespaceSelectorLabel | indent 12 }}
  {{- end }}
  {{- if $config.internalNamespace }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ $namespace }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
