apiVersion: batch/v1
kind: cronJob
metadata:
  name: {{ template "common.names.fullname" $ }}
  namespace: {{ .Release.Namespace }}
spec:
  schedule: "{{ required "Scheduler not defined" .Values.schedule }}"
  {{- if .Values.ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished }}
  {{- end }}
  {{- if .Values.successfulJobsHistoryLimit }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  {{- end }}
  {{- if .Values.failedJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  {{- end }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy | default "Replace" }}
  suspend: {{ .Values.suspend | default false }}
  serviceAccountName: {{ include "serviceAccountName" . }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.jobTemplate.backoffLimit | default 6 }}
      parallelism: {{ .Values.jobTemplate.parallelism | default 1 }}
      completions: {{ .Values.jobTemplate.completions | default 1}}
      activeDeadlineSeconds: {{ .Values.jobTemplate.activeDeadlineSeconds | default 100 }}
      template:
        spec:
          containers:
            - name: {{ template "common.names.fullname" $ }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
              image: "{{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: MY_JOB_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.jobIP
                - name: MY_JOB_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_NAMESPACE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_DEPLOYMENT_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['app.kubernetes.io/name']
                - name: OTEL_SERVICE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.labels['app.opentelemetry.io/service-name']
              {{- if .Values.env }}
                {{- toYaml .Values.env | nindent 16 }}
              {{- end }}
              {{- if .Values.containersSecondary }} {{ .Values.containersSecondary | toString | nindent 12 }}
              {{- end }}
          restartPolicy: OnFailure
