{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "serviceAccountName" . }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- include "labels.AppVersion" $ | nindent 4 }}
  {{- include "labels.kiali" $ | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}