{{- if .Values.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "common.names.fullname" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  endpoints:
    - honorLabels: true
      interval: {{ .Values.serviceMonitor.interval }}
      path: {{ .Values.serviceMonitor.url }}
      port: http
      scheme: http
      scrapeTimeout: 30s
  namespaceSelector:
    matchNames:
      - {{ template "common.names.namespace" $ }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" $ | nindent 6 }}
{{- end }}