{{- if .Values.configMap.injectFile.enabled }}
{{- range $key, $value := .Values.configMap.injectFile.itens }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ms-generic.names.injectFile.name" ( dict "name" $key "context" $)  }}
  namespace: {{ template "common.names.namespace" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
    {{- include "ms-generic.labels.AppVersion" $ | nindent 4 }}
    {{- include "ms-generic.labels.kiali" $ | nindent 4 }}
  {{- if $.Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" $.Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{ $value.name }}: |-
{{ (printf "%s" $value.content) | indent 4 }}
{{- end }}
{{- end }}