{{- if .Values.networkPolicy.egress.enabled }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-egress-{{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
spec:
  selector: all()
  types:
    - Egress
  egress:
    - action: Allow
      source:
        namespaceSelector: {{ printf "\"network.policy.egress/allow == '%s'\"" (include "common.names.name" .) }}
{{- end }}
