{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "common.names.fullname" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- include "ms-generic.AppVersion" $ | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "common.names.fullname" $ }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.metrics.resources.cpu.utilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          averageUtilization: {{ .Values.autoscaling.metrics.resources.cpu.utilizationPercentage }}
          type: Utilization
    {{- end }}
    {{- if .Values.autoscaling.metrics.resources.memory.utilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          averageUtilization: {{ .Values.autoscaling.metrics.resources.memory.utilizationPercentage }}
          type: Utilization
    {{- end }}  
    {{- if and .Values.autoscaling.metrics.pods.metricName .Values.autoscaling.metrics.pods.targetAverageValue }}
    - type: Pods
      pods:
        metric:
          name: {{ .Values.autoscaling.metrics.pods.metricName }}
        target:
          type: AverageValue
          averageValue: {{ .Values.autoscaling.metrics.pods.targetAverageValue }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleDown.value }}
        periodSeconds: {{ .Values.autoscaling.scaleDown.periodSeconds  }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.stabilizationWindowSeconds }}
      policies:
      - type: Pods
        value: {{ .Values.autoscaling.scaleUp.value }}
        periodSeconds: {{ .Values.autoscaling.scaleUp.periodSeconds }}
      selectPolicy: Max
{{- end }}
