{{- if .Values.ingress.enabled -}}
{{- $fullName := include "ms-generic.fullname" . -}}
{{- range .Values.ingress.items }}
---
{{- if and .className (not (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  {{- if not (hasKey .annotations "kubernetes.io/ingress.class") }}
  {{- $_ := set .annotations "kubernetes.io/ingress.class" .className}}
  {{- end }}
{{- end }}
{{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  {{- if $.Values.ingress.appendNamespace }}
  name: {{ template "common.names.fullname" $ }}-{{ template "common.names.namespace" $ }}{{- if .className }}-{{ .className }}{{- end }}
  {{- else }}
  name: {{ template "common.names.fullname" $ }}{{- if .className }}-{{ .className }}{{- end }}
  {{- end }}
  namespace: {{ template "common.names.namespace" $ }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- include "ms-generic.labels.AppVersion" $ | nindent 4 }}
  {{- include "ms-generic.labels.kiali" $ | nindent 4 }}
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .className (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .className }}
  {{- end }}
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ template "ms-generic.names.service.name" $ }}
                port:
                  number: {{ include "ms-generic.names.service.port" $ }}
              {{- else }}
              serviceName: {{ template "ms-generic.names.service.name" $ }}
              servicePort: {{ include "ms-generic.names.service.port" $ }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
{{- end }}
