{{- if .Values.networkPolicy.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-{{ template "common.names.name" $ }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    - from:
      - namespaceSelector:
          matchLabels:
            network.policy.ingress/allow: {{ template "common.names.name" . }}
{{- end }}
