{{- if .Values.networkPolicy.ingress.enabled }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-{{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
spec:
  selector: all()
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        namespaceSelector: {{ printf "\"network.policy.ingress/allow == '%s'\"" (include "common.names.name" .) }}
{{- end }}
