{{- if .Values.calicoPolicy.ingress.enabled }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-{{ template "common.names.name" . }}
  namespace: {{ template "common.names.namespace" . }}
spec:
  selector: all()
  types:
    - Ingress
  ingress:
    - action: Allow
      source:
        namespaceSelector: {{ printf "\"calico.policy/%s.%s == 'allow-ingress'\"" (include "common.names.name" .) (include "common.names.namespace" .) }}
{{- end }}
