{{- if .Values.secretProviderClass.enabled }}
{{- range .Values.secretProviderClass.itens }}
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ include "ms-generic.names.secretProviderClass.name" ( dict "provider" .provider "context" $)  }} 
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
    {{- if $.Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" $.Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  namespace: {{ template "common.names.namespace" $ }}
spec:
  provider: {{.provider}}
  secretObjects:
    - secretName: {{ include "ms-generic.names.secretProviderClass.secretName.name" ( dict "provider" .provider "context" $)  }} 
      type: Opaque
      data:
      {{- range .properties }}
        - objectName: {{ .objectName }}
          key: {{ .key }}
      {{- end }}     
  parameters:
    objects: |
        {{- range .properties }}
        - objectName: {{ .objectName }}
          objectType: {{ .objectType }}
        {{- end }}
{{- end }}
{{- end }}


