{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ms-generic.serviceAccountName" . }}
  labels: {{- include "common.labels.standard" $ | nindent 4 }}
  {{- include "ms-generic.labels.AppVersion" $ | nindent 4 }}
  {{- include "ms-generic.labels.kiali" $ | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if .Values.serviceAccount.extras }}
    {{- toYaml .Values.serviceAccount.extras | nindent 0 }}
{{- end }}
{{- end }}
