containers:
  volumeMounts:
    extra:
      enabled: true
      data:
        - name: tls-volume
          mountPath: /tls
volumes:
  extra:
    enabled: true
    data:
      - name: tls-volume
        emptyDir: {}
      - name: tls-secret
        secret:
          secretName: cert-tls-secret

initContainers:
  enabled : true
  extras:
    - name: generate-keystores
      image: eclipse-temurin:21-jre-alpine  # Imagem com keytool e openssl
      command:
        - /bin/bash
        - -c
        - |
          mkdir -p /tls
      
          echo "Criando truststore..."
          keytool -importcert -noprompt \
            -file /mnt/secret/ca.crt \
            -alias rabbitmq-ca \
            -keystore /tls/server-truststore.p12 \
            -storepass changeit \
            -storetype PKCS12

          echo "Criando keystore..."
          openssl pkcs12 -export \
            -in /mnt/secret/client.crt \
            -inkey /mnt/secret/client.key \
            -out /tls/client-keystore.p12 \
            -name rabbitmq-client \
            -passout pass:changeit

      volumeMounts:
        - name: tls-volume
          mountPath: /tls
        - name: tls-secret
          mountPath: /mnt/secret