initContainers:
  enabled: true
  waitForCmd:
    command: ['sh', '-c', while true; do STATUS=""; nc -z redis 6379 || STATUS="$STATUS Redis"; if [ -z "$STATUS" ]; then echo "Todos os serviços estão disponíveis!"; break; fi; echo "Aguardando os seguintes serviços:$STATUS..."; sleep 10; done']