{{- if .Values.secrets }}
{{- $config := .Values.secrets.dockerconfigjson }}
{{- range $confKey, $confValue := $config }}
{{- range $j, $namespace := $confValue.namespaces }}
{{- if $confValue.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $confKey }}
  namespace: {{ $namespace }}
  labels:
    release/name: "{{ $.Release.Name }}"
    release/revision: "{{ $.Release.Revision }}"
type: kubernetes.io/dockerconfigjson
data:
{{- if $confValue.data.encode }}
  .dockerconfigjson: {{ $confValue.data.encode }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
