{{- if .Values.secrets }}
{{- $config := .Values.secrets.opaque }}
{{- range $confKey, $confValue := $config }}
{{- range $j, $namespace := $confValue.namespaces }}
{{- if $confValue.data }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $confKey }}
  namespace: {{ $namespace }}
  labels:
    release/name: "{{ $.Release.Name }}"
    release/revision: "{{ $.Release.Revision }}"
type: Opaque
data:
  {{- range $key, $value := $confValue.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
