
{{- /* Cria contexto completo para o Prometheus Stack */ -}}
{{- $prometheusValues := $.Values.kubePrometheusStack | default dict -}}
{{- $prometheusContext := dict 
  "Chart" .Chart
  "Release" .Release
  "Values" $prometheusValues
-}}

{{- printf "Contexto do Prometheus: %s" (toYaml $prometheusContext) | nindent 0 -}}

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ printf "%s-%s" (include "kube-prometheus-stack.fullname" $prometheusContext) "pax-pod-memory.rules" | trunc 63 | trimSuffix "-" }}
  namespace: {{ template "kube-prometheus-stack.namespace" $prometheusContext }}
  labels:
    app: {{ template "kube-prometheus-stack.name" $prometheusContext }}
{{ include "kube-prometheus-stack.labels" $prometheusContext | indent 4 }}
{{- if $prometheusContext.Values.defaultRules }}
  {{- if $prometheusContext.Values.defaultRules.labels }}
{{ toYaml $prometheusContext.Values.defaultRules.labels | indent 4 }}
  {{- end }}
  {{- if $prometheusContext.Values.defaultRules.annotations }}
  annotations:
{{ toYaml $prometheusContext.Values.defaultRules.annotations | indent 4 }}
  {{- end }}
{{- end }}
spec:
  groups:
  - name: pax.k8s.rules.pod_memory
    rules:
    # 1. Alerta para Pods Finalizados por OOM
    - alert: PodOOMKilled
      expr: |-
        kube_pod_container_status_last_terminated_reason{job="kube-state-metrics", reason="OOMKilled"} == 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pod finalizado por OOM (Out of Memory)"
        description: "O container {{`{{`}} $labels.container {{`}}`}} no pod {{`{{`}} $labels.pod {{`}}`}} (namespace: {{`{{`}} $labels.namespace {{`}}`}}) foi finalizado por OOMKilled. Workload: {{`{{`}} $labels.owner_kind {{`}}`}}/{{`{{`}} $labels.owner_name {{`}}`}}"
    
    # 2. Alerta para Subutilização de Memória (vs Request)
    - alert: PodMemoryRequestUnderutilized
      expr: >-
        sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", container!="", image!=""}) by (namespace, pod, container)
        /
        sum(kube_pod_container_resource_requests{job="kube-state-metrics", resource="memory", unit="byte"} > 0) by (namespace, pod, container)
        < 0.80
      for: 1h
      labels:
        severity: warning
      annotations:
        summary: "Subutilização de memória (request muito alto)"

    # 3. Alerta para Uso Alto de Memória (vs Limit) - NOVO
    - alert: PodMemoryUsageNearLimit
      expr: >-
        sum(container_memory_working_set_bytes{job="kubelet", metrics_path="/metrics/cadvisor", container!="", image!=""}) by (namespace, pod, container)
        /
        sum(kube_pod_container_resource_limits{job="kube-state-metrics", resource="memory", unit="byte"} > 0) by (namespace, pod, container)
        > 0.96
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "Uso de memória próximo ao limite (96%)"