name: Delete Draft Releases Manually
on:
  workflow_dispatch:  # Só roda quando acionado manualmente

jobs:
  delete-drafts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete draft releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # (O mesmo script da Opção 1)
          sudo apt-get install -y jq
          DRAFT_RELEASES=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases" \
            | jq '.[] | select(.draft == true) | .id')
          
          for release_id in $DRAFT_RELEASES; do
            echo "Deleting draft release ID $release_id"
            curl -X DELETE -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases/$release_id"
          done