name: Delete Draft Releases Manually
on:
  workflow_dispatch:

jobs:
  delete-drafts:
    runs-on: ubuntu-latest
    steps:
      - name: Delete draft releases
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Configuração inicial tolerante a falhas
          sudo apt-get update -y
          sudo apt-get install -y jq curl || echo "Dependências instaladas com warning"

          DELETED_COUNT=0
          PAGE=1
          PER_PAGE=100
          MAX_PAGES=10
          API_URL="https://api.github.com/repos/$REPO_OWNER/$REPO_NAME/releases"

          echo "=== INICIANDO LIMPEZA DE DRAFTS ==="

          while [[ $PAGE -le $MAX_PAGES ]]; do
            echo "🔍 Buscando página $PAGE..."
            
            # Requisição com timeout e tratamento robusto
            RELEASES_JSON=$(curl -sf \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              --connect-timeout 10 \
              "$API_URL?page=$PAGE&per_page=$PER_PAGE") || {
                echo "⚠️ Falha na API ao buscar página $PAGE"
                break
              }

            # Verificação EXTREMAMENTE robusta do JSON
            if ! jq -e 'if type=="array" then true else false end' <<< "${RELEASES_JSON:-[]}" >/dev/null; then
              echo "ℹ️ Nenhuma release encontrada (página $PAGE)"
              break
            fi

            # Processamento seguro de drafts
            DRAFT_IDS=$(echo "${RELEASES_JSON:-[]}" | jq -r '.[] | select(.draft==true) | .id' 2>/dev/null || true)

            if [[ -z "$DRAFT_IDS" ]]; then
              echo "➡️ Nenhum draft na página $PAGE"
              ((PAGE++))
              continue
            fi

            # Deleção com verificação explícita
            for release_id in $DRAFT_IDS; do
              echo "🗑️ Processando draft ID $release_id..."
              
              RESPONSE=$(curl -sf -X DELETE \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                -w "%{http_code}" \
                -o /dev/null \
                --connect-timeout 10 \
                "$API_URL/$release_id")

              if [[ "${RESPONSE:-}" == "204" ]]; then
                echo "✅ Sucesso ao deletar $release_id"
                ((DELETED_COUNT++))
              else
                echo "❌ Falha ao deletar $release_id (status: ${RESPONSE:-unknown})"
              fi
            done

            ((PAGE++))
          done

          echo "=================================="
          echo "🚀 RESUMO FINAL"
          echo "📌 Páginas processadas: $((PAGE-1))"
          echo "🗑️ Drafts deletados: $DELETED_COUNT"
          echo "=================================="